name: Image Generator

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: streak
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Streak Image
        run: |
          mkdir -p images
          curl -o images/streak.svg "https://streak-stats.demolab.com/?user=mattpidden&hide_border=true&date_format=M%20j%5B%2C%20Y%5D&background=EB545400&currStreakNum=EB582C&currStreakLabel=EB5517&sideNums=38DC16&sideLabels=209712&dates=838383&stroke=C5C5C578"
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "generated images"
          git push
