name: Image Generator

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-streak
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Streak Image
        run: |
          mkdir -p images
          curl -o images/streak.png "https://streak-stats.demolab.com?user=mattpidden&theme=dark&hide_border=true&date_format=M%20j%5B%2C%20Y%5D&type=png"
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "generated images"
          git push
